culimating_course_dict = {
    "EXRCR": ["EES85"],
    "SXRKE": ["SLS22"],
    "MXRKE": ["MGS22"],
    "HXRKE": ["HUS22"],
    "MXRCE": ["MES22"],
    "SXRPE": ["SPS22"],
    "HXRCE": ["HGS44"],
    "MXRNE": ["MRS22"],
    "SXRXE": ["SCS22"],
    "SXRUE": ["SES22"],
}

culimating_course_to_exam_dict = {
    "EES85" : "EXRCR",
    "SLS22" : "SXRKE",
    "MGS22" : "MXRKE",
    "HUS22" : "HXRKE",
    "MES22" : "MXRCE",
    "SPS22" : "SXRPE",
    "HGS44" : "HXRCE",
    "MRS22" : "MXRNE",
    "SCS22" : "SXRXE",
    "SES22" : "SXRUE",
}


administration_dates_dict = {
    "January2024": {
        "ELA": {"Day": "1", "Time": "AM", "ExamCode": "EXRCR"},
        "LE": {"Day": "1", "Time": "PM", "ExamCode": "SXRKR"},
        "Geo": {"Day": "2", "Time": "AM", "ExamCode": "MXRKR"},
        "US": {"Day": "2", "Time": "AM", "ExamCode": "HXRKR"},
        "AlgI": {"Day": "2", "Time": "PM", "ExamCode": "MXRCR"},
        "Phys": {"Day": "2", "Time": "PM", "ExamCode": "SXRPR"},
        "Global": {"Day": "3", "Time": "AM", "ExamCode": "HXRCR"},
        "AlgII/Trig": {"Day": "3", "Time": "PM", "ExamCode": "MXRNR"},
        "Chem": {"Day": "4", "Time": "AM", "ExamCode": "SXRXR"},
        "ES": {"Day": "4", "Time": "AM", "ExamCode": "SXRUR"},
    },
    "January2023": {
        "ELA": {"Day": "1", "Time": "AM", "ExamCode": "EXRCR"},
        "LE": {"Day": "1", "Time": "PM", "ExamCode": "SXRKR"},
        "Geo": {"Day": "2", "Time": "AM", "ExamCode": "MXRKR"},
        "AlgI": {"Day": "2", "Time": "PM", "ExamCode": "MXRCR"},
        "Phys": {"Day": "2", "Time": "PM", "ExamCode": "SXRPR"},
        "Global": {"Day": "3", "Time": "AM", "ExamCode": "HXRCR"},
        "AlgII/Trig": {"Day": "3", "Time": "PM", "ExamCode": "MXRNR"},
        "Chem": {"Day": "4", "Time": "AM", "ExamCode": "SXRXR"},
        "ES": {"Day": "4", "Time": "AM", "ExamCode": "SXRUR"},
    },
    "June2023": {
        "US": {"Day": "0", "Time": "AM", "ExamCode": "HXRKE"},
        "ELA": {"Day": "1", "Time": "AM", "ExamCode": "EXRCE"},
        "LE": {"Day": "1", "Time": "PM", "ExamCode": "SXRKE"},
        "Global": {"Day": "2", "Time": "AM", "ExamCode": "HXRCE"},
        "AlgI": {"Day": "2", "Time": "PM", "ExamCode": "MXRCE"},
        "ES": {"Day": "3", "Time": "AM", "ExamCode": "SXRUE"},
        "Chem": {"Day": "3", "Time": "PM", "ExamCode": "SXRXE"},
        "Geo": {"Day": "4", "Time": "AM", "ExamCode": "MXRKE"},
        "AlgII/Trig": {"Day": "5", "Time": "AM", "ExamCode": "MXRNE"},
        "Phys": {"Day": "6", "Time": "AM", "ExamCode": "SXRPE"},
    },
}


conflict_sections = [
    31,
    32,
    33,
    34,
    35,
    36,
    37,
    38,
    39,
    51,
    52,
    53,
    54,
    55,
    56,
    57,
    58,
    59,
    81,
    82,
    83,
    84,
    85,
    86,
    87,
    88,
]
